version: '3.8'

services:
  ai-platform:
    build: .
    container_name: ai-chatbot-platform
    ports:
      - "5000:5000"  # Backend API
      - "3000:3000"  # Frontend (if needed)
    environment:
      - NODE_ENV=production
      - PORT=5000
      - FRONTEND_PORT=3000
    env_file:
      - .env
    volumes:
      - ./database:/app/database
      - ./uploads:/app/uploads
      - ./containers:/app/containers
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ai-network

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: ai-platform-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ai-platform
    restart: unless-stopped
    networks:
      - ai-network

networks:
  ai-network:
    driver: bridge

volumes:
  database:
  uploads:
  containers:
  logs:
